feat: Add IONOS Virtual Data Center
meshcloud/building-blocks pull request #43
Opened 2023-11-10 10:55 UTC by Jelledb

2023-11-10 11:01 UTC, felixzieger commented
Let's put IONOS on the root level of the repo.

2023-11-13 12:21 UTC, ishabakeh requested changes
Looks good, 
Would you change the logo file name to just "icon.png" it will be leveraged in other areas, we have to also change it in other modules.

2023-11-13 12:22 UTC, ishabakeh commented
> Let's put IONOS on the root level of the repo.

I am more in favor of "other providers", otherwise we have to move everything to the root of the repo

2023-11-14 09:00 UTC, malhussan approved these changes
IMO it could also fit in top level as a platform that can run workload and can possibly expand to submodules for different offered IONOS services

2023-11-14 09:00 UTC, malhussan commented on other-providers/ionos/virtual-data-center/README.md
> +    - `IONOS_TOKEN`
t: or IONOS_USERNAME and IONOS_PASSWORD

2023-11-14 12:04 UTC, Jelledb commented
> IMO it could also fit in top level as a platform that can run workload and can possibly expand to submodules for different offered IONOS services

This argument in the end made me choose for the top level. I think it makes a lot of sense.

2023-11-14 12:48 UTC, ishabakeh approved these changes

2023-11-14 12:48 UTC, merged